import os
from lxml import etree
W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
def w(t): return '{%s}%s' % (W, t)
BASE = os.path.dirname(os.path.abspath(__file__)); DOC = os.path.join(BASE, 'unpacked', 'word', 'document.xml')
tree = etree.parse(DOC); root = tree.getroot(); body = root.find(w('body'))
def ptext(p): return ''.join(t.text or '' for t in p.iter(w('t')))
p = next(p for p in body.findall(w('p')) if ptext(p).startswith('Use of generative AI.'))
p.findall(w('r'))[1].find(w('t')).text = (
    'Claude (Anthropic) was used during this work for coding assistance (writing and debugging the analysis, '
    'evaluation, figure-rendering and document-formatting scripts released with the code), for language editing, '
    'and for drafting revisions of existing text in response to reviewer and audit comments. The study design, '
    'the data-processing and evaluation decisions, the experiments and all reported results are the authors’ own, '
    'and no references were generated by it. All content was reviewed and approved by the authors, who are fully '
    'responsible for the final manuscript.')
tree.write(DOC, xml_declaration=True, encoding='UTF-8', standalone=True); print(ptext(p))
