import os
from lxml import etree
W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
def w(t): return '{%s}%s' % (W, t)
BASE = os.path.dirname(os.path.abspath(__file__)); DOC = os.path.join(BASE, 'unpacked', 'word', 'document.xml')
tree = etree.parse(DOC); root = tree.getroot(); body = root.find(w('body'))
def ptext(p): return ''.join(t.text or '' for t in p.iter(w('t')))
p = next(p for p in body.findall(w('p')) if ptext(p).startswith('Use of generative AI.'))
p.findall(w('r'))[1].find(w('t')).text = (
    'Claude (Anthropic) was used during manuscript preparation for language editing, for drafting revisions of '
    'existing text in response to reviewer and audit comments, and for generating the figure-rendering and '
    'document-formatting scripts released with the code. It was not used to design the study, process the data, '
    'run the experiments, or produce any reported result, and no references were generated by it. All content was '
    'reviewed and approved by the authors, who are fully responsible for the final manuscript.')
tree.write(DOC, xml_declaration=True, encoding='UTF-8', standalone=True); print(ptext(p))
